# Generated by Django 2.2.6 on 2019-12-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='con_image',
            field=models.ImageField(default='panda.jpg', upload_to='content_images'),
        ),
    ]
