# Generated by Django 2.2.6 on 2019-12-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0002_post_con_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='con_image',
            field=models.ImageField(upload_to='content_images'),
        ),
    ]
