# Generated by Django 2.2.6 on 2019-12-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0003_auto_20191205_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='con_image',
            field=models.ImageField(default='panda.jpg', upload_to='content_images'),
        ),
    ]
