# Generated by Django 2.1.5 on 2019-12-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_website', '0005_post_con_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='con_image2',
        ),
    ]
